import numpy as np
import matplotlib.pyplot as plt


euler= np.genfromtxt("euler.txt")
leapfrog= np.genfromtxt("leapfrog.txt")
rungek4 = np. genfromtxt("rungek4.txt")

euler2= np.genfromtxt("eulerdt2.txt")
leapfrog2= np.genfromtxt("leapfrogdt2.txt")
rungek42= np. genfromtxt("rungek4dt2.txt")

euler3= np.genfromtxt("eulerdt3.txt")
leapfrog3= np.genfromtxt("leapfrogdt3.txt")
rungek43= np. genfromtxt("rungek4dt3.txt")

# x vs y  3 metodos y 3 dts.

plt.figure(figsize=(16,12))
plt.subplot(3,3,1)
plt.plot(euler[:,1],euler[:,2], color= 'g')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("Euler: X vs Y")

plt.subplot(3,3,2)
plt.plot(leapfrog[:,1],leapfrog[:,2], color= 'c')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("leapfrog: X vs Y")

plt.subplot(3,3,3)
plt.plot(rungek4[:,1],rungek4[:,2], color= 'm')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("RK4: X vs Y")

plt.subplot(3,3,4)
plt.plot(euler2[:,1],euler2[:,2], color= 'g')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("Euler: X vs Y")

plt.subplot(3,3,5)
plt.plot(leapfrog2[:,1],leapfrog2[:,2], color= 'c')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("leapfrog: X vs Y")

plt.subplot(3,3,6)
plt.plot(rungek42[:,1],rungek42[:,2], color= 'm')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("RK4: X vs Y")

plt.subplot(3,3,7)
plt.plot(euler3[:,1],euler3[:,2], color= 'g')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("Euler: X vs Y")

plt.subplot(3,3,8)
plt.plot(leapfrog3[:,1],leapfrog3[:,2], color= 'c')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("leapfrog: X vs Y")

plt.subplot(3,3,9)
plt.plot(rungek43[:,1],rungek43[:,2], color= 'm')
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.title("RK4: X vs Y")

plt.subplots_adjust(hspace=0.5)
plt.savefig("XY_met_dt.pdf")


# vy vs vx

plt.figure(figsize=(16,12))
plt.subplot(3,3,1)
plt.plot(euler[:,3],euler[:,4], color= 'g')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("Euler: Vx vs Vy")

plt.subplot(3,3,2)
plt.plot(leapfrog[:,3],leapfrog[:,4], color= 'c')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("leapfrog: Vx vs Vy")

plt.subplot(3,3,3)
plt.plot(rungek4[:,3],rungek4[:,4], color= 'm')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("RK4: Vx vs Vy")

plt.subplot(3,3,4)
plt.plot(euler2[:,3],euler2[:,4], color= 'g')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("Euler: Vx vs Vy")

plt.subplot(3,3,5)
plt.plot(leapfrog2[:,3],leapfrog2[:,4], color= 'c')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("leapfrog: Vx vs Vy")

plt.subplot(3,3,6)
plt.plot(rungek42[:,3],rungek42[:,4], color= 'm')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("RK4: Vx vs Vy")

plt.subplot(3,3,7)
plt.plot(euler3[:,3],euler3[:,4], color= 'g')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("Euler: Vx vs Vy")

plt.subplot(3,3,8)
plt.plot(leapfrog3[:,3],leapfrog3[:,4], color= 'c')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("leapfrog: Vx vs Vy")

plt.subplot(3,3,9)
plt.plot(rungek43[:,3],rungek43[:,4], color= 'm')
plt.xlabel("Vx(AU/yr)")
plt.ylabel("Vy(AU/yr)")
plt.grid()
plt.title("RK4: Vx vs Vy")

plt.subplots_adjust(hspace=0.5)
plt.savefig("VxVy_met_dt.pdf")

#momentun angular

plt.figure(figsize=(16,12))
plt.subplot(3,3,1)
plt.plot(euler[:,0],euler[:,5], color= 'g')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("Euler: Momentum")

plt.subplot(3,3,2)
plt.plot(leapfrog[:,0],leapfrog[:,5], color= 'c')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("leapfrog: Momentum")

plt.subplot(3,3,3)
plt.plot(rungek4[:,0],rungek4[:,5], color= 'm')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("RK4: Momentum")

plt.subplot(3,3,4)
plt.plot(euler2[:,0],euler2[:,5], color= 'g')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("Euler: Momentum")

plt.subplot(3,3,5)
plt.plot(leapfrog2[:,0],leapfrog2[:,5], color= 'c')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("leapfrog: Momentum")

plt.subplot(3,3,6)
plt.plot(rungek42[:,0],rungek42[:,5], color= 'm')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("RK4: Momentum")

plt.subplot(3,3,7)
plt.plot(euler3[:,0],euler3[:,5], color= 'g')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("Euler: Momentum")

plt.subplot(3,3,8)
plt.plot(leapfrog3[:,0],leapfrog3[:,5], color= 'c')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("leapfrog: Momentum")

plt.subplot(3,3,9)
plt.plot(rungek43[:,0],rungek43[:,5], color= 'm')
plt.xlabel("t")
plt.ylabel("")
plt.grid()
plt.title("RK4: Momentum")

plt.subplots_adjust(hspace=0.5)
plt.savefig("Mome_met_dt.pdf")

# energia del sistema 

plt.figure(figsize=(22,12))
plt.subplot(3,3,1)
plt.plot(euler[:,0],euler[:,8], color= 'darkgreen', label="E. total")
plt.plot(euler[:,0],euler[:,7], color= 'olivedrab', label="E.potencial")
plt.plot(euler[:,0],euler[:,6], color= 'darkseagreen', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("Euler: Energia sistema")

plt.subplot(3,3,2)
plt.plot(leapfrog[:,0],leapfrog[:,8], color= 'blue',label="E. total")
plt.plot(leapfrog[:,0],leapfrog[:,7], color= 'mediumturquoise',label="E.potencial")
plt.plot(leapfrog[:,0],leapfrog[:,6], color= 'dodgerblue', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("leapfrog: Energia sistema")

plt.subplot(3,3,3)
plt.plot(rungek4[:,0],rungek4[:,8], color= 'deeppink',label="E. total")
plt.plot(rungek4[:,0],rungek4[:,7], color= 'purple',label="E.potencial")
plt.plot(rungek4[:,0],rungek4[:,6], color= 'darkorchid', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("RK4: Energia sistema")

plt.subplot(3,3,4)
plt.plot(euler2[:,0],euler2[:,8], color= 'darkgreen', label="E. total")
plt.plot(euler2[:,0],euler2[:,7], color= 'olivedrab', label="E.potencial")
plt.plot(euler2[:,0],euler2[:,6], color= 'darkseagreen', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("Euler: Energia sistema")

plt.subplot(3,3,5)
plt.plot(leapfrog2[:,0],leapfrog2[:,8], color= 'blue',label="E. total")
plt.plot(leapfrog2[:,0],leapfrog2[:,7], color= 'mediumturquoise',label="E.potencial")
plt.plot(leapfrog2[:,0],leapfrog2[:,6], color= 'dodgerblue', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("leapfrog: Energia sistema")

plt.subplot(3,3,6)
plt.plot(rungek42[:,0],rungek42[:,8], color= 'deeppink',label="E. total")
plt.plot(rungek42[:,0],rungek42[:,7], color= 'purple',label="E.potencial")
plt.plot(rungek42[:,0],rungek42[:,6], color= 'darkorchid', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("RK4: Energia sistema")

plt.subplot(3,3,7)
plt.plot(euler3[:,0],euler3[:,8], color= 'darkgreen', label="E. total")
plt.plot(euler3[:,0],euler3[:,7], color= 'olivedrab', label="E.potencial")
plt.plot(euler3[:,0],euler3[:,6], color= 'darkseagreen', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("Euler: Energia sistema")

plt.subplot(3,3,8)
plt.plot(leapfrog3[:,0],leapfrog3[:,8], color= 'blue',label="E. total")
plt.plot(leapfrog3[:,0],leapfrog3[:,7], color= 'mediumturquoise',label="E.potencial")
plt.plot(leapfrog3[:,0],leapfrog3[:,6], color= 'dodgerblue', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("leapfrog: Energia sistema")

plt.subplot(3,3,9)
plt.plot(rungek43[:,0],rungek43[:,8], color= 'deeppink',label="E. total")
plt.plot(rungek43[:,0],rungek43[:,7], color= 'purple',label="E.potencial")
plt.plot(rungek43[:,0],rungek43[:,6], color= 'darkorchid', label="E.cinetica")
plt.xlabel("t")
plt.ylabel("E")
#plt.grid()
plt.legend()
plt.title("RK4: Energia sistema")

plt.subplots_adjust(hspace=0.5)
plt.savefig("Ener_met_dt.pdf")


plt.figure(figsize=(8,12))

plt.subplot(3,1,1)
plt.plot(euler[:,0],euler[:,8], color= 'darkgreen', label="Eu")
plt.plot(leapfrog[:,0],leapfrog[:,8], color= 'blue',label="LF")
plt.plot(rungek4[:,0],rungek4[:,8], color= 'deeppink',label="RK")
plt.legend()
#plt.grid()
plt.xlabel("t")
plt.ylabel("E")
plt.title("E. sistema: Comparacion de metodos. Dt=0.01")

plt.subplot(3,1,2)
plt.plot(euler2[:,0],euler2[:,8], color= 'darkgreen', label="Eu")
plt.plot(leapfrog2[:,0],leapfrog2[:,8], color= 'blue',label="LF")
plt.plot(rungek42[:,0],rungek42[:,8], color= 'deeppink',label="RK")
plt.legend()
#plt.grid()
plt.xlabel("t")
plt.ylabel("E")
plt.title("E. sistema: Comparacion de metodos. Dt=0.001")

plt.subplot(3,1,3)
plt.plot(euler3[:,0],euler3[:,8], color= 'darkgreen', label="Eu")
plt.plot(leapfrog3[:,0],leapfrog3[:,8], color= 'blue',label="LF")
plt.plot(rungek43[:,0],rungek43[:,8], color= 'deeppink',label="RK")
plt.legend()
#plt.grid()
plt.xlabel("t")
plt.ylabel("E")
plt.title("E. sistema: Comparacion de metodos. Dt=0.0001")
plt.subplots_adjust(hspace=0.5)
plt.savefig("Enertotal_met_dt.pdf")




